package com.microsoft.dynamics.ax;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-11T09:57:33.899-03:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/services", name = "ItemService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ItemService {

    @WebResult(name = "ItemServiceFindResponse", targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/services", partName = "parameters")
    @Action(input = "http://schemas.microsoft.com/dynamics/2008/01/services/ItemService/find", output = "http://schemas.microsoft.com/dynamics/2008/01/services/ItemService/findResponse", fault = {@FaultAction(className = ItemServiceFindAifFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/dynamics/2008/01/services/ItemService/findAifFaultFault")})
    @WebMethod(action = "http://schemas.microsoft.com/dynamics/2008/01/services/ItemService/find")
    public ItemServiceFindResponse find(
        @WebParam(partName = "parameters", name = "ItemServiceFindRequest", targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/services")
        ItemServiceFindRequest parameters
    ) throws ItemServiceFindAifFaultFaultFaultMessage;

    @WebResult(name = "ItemServiceCreateResponse", targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/services", partName = "parameters")
    @Action(input = "http://schemas.microsoft.com/dynamics/2008/01/services/ItemService/create", output = "http://schemas.microsoft.com/dynamics/2008/01/services/ItemService/createResponse", fault = {@FaultAction(className = ItemServiceCreateAifFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/dynamics/2008/01/services/ItemService/createAifFaultFault")})
    @WebMethod(action = "http://schemas.microsoft.com/dynamics/2008/01/services/ItemService/create")
    public ItemServiceCreateResponse create(
        @WebParam(partName = "parameters", name = "ItemServiceCreateRequest", targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/services")
        ItemServiceCreateRequest parameters
    ) throws ItemServiceCreateAifFaultFaultFaultMessage;

    @WebResult(name = "ItemServiceFindKeysResponse", targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/services", partName = "parameters")
    @Action(input = "http://schemas.microsoft.com/dynamics/2008/01/services/ItemService/findKeys", output = "http://schemas.microsoft.com/dynamics/2008/01/services/ItemService/findKeysResponse", fault = {@FaultAction(className = ItemServiceFindKeysAifFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/dynamics/2008/01/services/ItemService/findKeysAifFaultFault")})
    @WebMethod(action = "http://schemas.microsoft.com/dynamics/2008/01/services/ItemService/findKeys")
    public ItemServiceFindKeysResponse findKeys(
        @WebParam(partName = "parameters", name = "ItemServiceFindKeysRequest", targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/services")
        ItemServiceFindKeysRequest parameters
    ) throws ItemServiceFindKeysAifFaultFaultFaultMessage;

    @WebResult(name = "ItemServiceReadResponse", targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/services", partName = "parameters")
    @Action(input = "http://schemas.microsoft.com/dynamics/2008/01/services/ItemService/read", output = "http://schemas.microsoft.com/dynamics/2008/01/services/ItemService/readResponse", fault = {@FaultAction(className = ItemServiceReadAifFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/dynamics/2008/01/services/ItemService/readAifFaultFault")})
    @WebMethod(action = "http://schemas.microsoft.com/dynamics/2008/01/services/ItemService/read")
    public ItemServiceReadResponse read(
        @WebParam(partName = "parameters", name = "ItemServiceReadRequest", targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/services")
        ItemServiceReadRequest parameters
    ) throws ItemServiceReadAifFaultFaultFaultMessage;
}
