
package com.microsoft.dynamics.ax;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-11T09:57:33.588-03:00
 * Generated source version: 2.7.6
 * 
 */
public final class ItemService_BasicHttpBindingItemService_Client {

	private static final QName SERVICE_NAME = new QName("http://schemas.microsoft.com/dynamics/2008/01/services", "ItemService");

	private ItemService_BasicHttpBindingItemService_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = ItemService_Service.WSDL_LOCATION;
		
//		if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
//			File wsdlFile = new File(args[0]);
//			try {
//				if (wsdlFile.exists()) {
//					wsdlURL = wsdlFile.toURI().toURL();
//				} else {
//					wsdlURL = new URL(args[0]);
//				}
//			} catch (MalformedURLException e) {
//				e.printStackTrace();
//			}
//		}
		wsdlURL = new URL("http://Matiass-MacBook-Pro-3.local:8088/mockBasicHttpBinding_ItemService?wsdl");
		ItemService_Service ss = new ItemService_Service(wsdlURL, SERVICE_NAME);
		ItemService port = ss.getBasicHttpBindingItemService();  

//		{
//			System.out.println("Invoking find...");
//			com.microsoft.dynamics.ax.ItemServiceFindRequest _find_parameters = null;
//			try {
//				com.microsoft.dynamics.ax.ItemServiceFindResponse _find__return = port.find(_find_parameters);
//				System.out.println("find.result=" + _find__return);
//
//			} catch (ItemServiceFindAifFaultFaultFaultMessage e) { 
//				System.out.println("Expected exception: ItemService_find_AifFaultFault_FaultMessage has occurred.");
//				System.out.println(e.toString());
//			}
//		}
		{
			System.out.println("Invoking create...");
			com.microsoft.dynamics.ax.ItemServiceCreateRequest _create_parameters = null;
			
			ObjectFactory of = new ObjectFactory();
			_create_parameters = of.createItemServiceCreateRequest();
			
			AxdItem item = of.createAxdItem();
		
			_create_parameters.setItem(item);
			
			AxdEntityInventTable inventTableItem = of.createAxdEntityInventTable();
			
			inventTableItem.setItemId(of.createAxdEntityInventTableItemId("ACA VA EL ItemId"));
			
			inventTableItem.setDimGroupId("aca va el dim group id");
			
			inventTableItem.setItemGroupId("aca va el item group id");
			
			inventTableItem.setItemName(of.createAxdEntityInventTableItemName("aca va el item name"));
			
			inventTableItem.setModelGroupId("aca va el model group id");
			
			item.getInventTable().add(inventTableItem);
		
        	
			try {
				com.microsoft.dynamics.ax.ItemServiceCreateResponse _create__return = port.create(_create_parameters);
				System.out.println("create.result=" + _create__return);
				for (EntityKey entityKey : _create__return.getEntityKeyList().getEntityKey()) {
					System.out.println(" -- new entity key");
					for (KeyField keyField: entityKey.getKeyData().getKeyField()) {
						System.out.println(" -- --> "+keyField.getField()+" : "+ keyField.getValue());
					} 
				}

			} catch (ItemServiceCreateAifFaultFaultFaultMessage e) { 
				System.out.println("Expected exception: ItemService_create_AifFaultFault_FaultMessage has occurred.");
				System.out.println(e.toString());
			}
		}
//		{
//			System.out.println("Invoking findKeys...");
//			com.microsoft.dynamics.ax.ItemServiceFindKeysRequest _findKeys_parameters = null;
//			try {
//				com.microsoft.dynamics.ax.ItemServiceFindKeysResponse _findKeys__return = port.findKeys(_findKeys_parameters);
//				System.out.println("findKeys.result=" + _findKeys__return);
//
//			} catch (ItemServiceFindKeysAifFaultFaultFaultMessage e) { 
//				System.out.println("Expected exception: ItemService_findKeys_AifFaultFault_FaultMessage has occurred.");
//				System.out.println(e.toString());
//			}
//		}
//		{
//			System.out.println("Invoking read...");
//			com.microsoft.dynamics.ax.ItemServiceReadRequest _read_parameters = null;
//			try {
//				com.microsoft.dynamics.ax.ItemServiceReadResponse _read__return = port.read(_read_parameters);
//				System.out.println("read.result=" + _read__return);
//
//			} catch (ItemServiceReadAifFaultFaultFaultMessage e) { 
//				System.out.println("Expected exception: ItemService_read_AifFaultFault_FaultMessage has occurred.");
//				System.out.println(e.toString());
//			}
//		}

		System.exit(0);
	}

}
