
package com.microsoft.dynamics.ax;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-11T09:57:33.823-03:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "AifFault", targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")
public class ItemServiceFindAifFaultFaultFaultMessage extends Exception {
    
    private com.microsoft.dynamics.ax.AifFault aifFault;

    public ItemServiceFindAifFaultFaultFaultMessage() {
        super();
    }
    
    public ItemServiceFindAifFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ItemServiceFindAifFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ItemServiceFindAifFaultFaultFaultMessage(String message, com.microsoft.dynamics.ax.AifFault aifFault) {
        super(message);
        this.aifFault = aifFault;
    }

    public ItemServiceFindAifFaultFaultFaultMessage(String message, com.microsoft.dynamics.ax.AifFault aifFault, Throwable cause) {
        super(message, cause);
        this.aifFault = aifFault;
    }

    public com.microsoft.dynamics.ax.AifFault getFaultInfo() {
        return this.aifFault;
    }
}
